{% set sdata = load_setup_py_data(setup_file="../../../setup.py", from_recipe_dir=True) %}

package:
  name: {{ sdata['name'] }}
  version: {{ VERSION }}

source:
  url: ../../../dist/{{ sdata['name'] }}-{{ VERSION }}-py3-none-any.whl

build:
  noarch: python

requirements:
  host:
    - python {{ sdata['python_requires'] }}
    {% for dep in sdata['extras_require']['build'] %}
    - {{ dep }}
    {% endfor %}
  run:
    - python {{ sdata['python_requires'] }}
    - geoviews-core =={{ sdata['version'] }}
    {% for dep in sdata['extras_require']['recommended'] %}
    - {{ dep if dep != 'geopandas' else 'geopandas-base'}}
    {% endfor %}

about:
  home: {{ sdata['url'] }}
  summary: {{ sdata['description'] }}
  license: {{ sdata['license'] }}
