{% set sdata = load_setup_py_data() %}

package:
  name: geoviews
  version: {{ sdata['version'] }}

source:
  path: ..

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - holoviews >=1.9.0
    - jupyter
    - notebook
    - cartopy
    - bokeh >=0.12.10

about:
  home: geo.holoviews.org
  summary: GeoViews is a Python library that makes it easy to explore and visualize geographical, meteorological, and oceanographic datasets, such as those used in weather, climate, and remote sensing research.
  license: BSD 3-Clause
